---
- name: kvm provision
  hosts: localhost
  become: true
  
  tasks:
    - name: get vm list
      community.libvirt.virt:
        command: list_vms
      register: existing_vm
      changed_when: no
    
    - name: vm define
      ansible.builtin.include_tasks: kvm-provision.yaml
      when: "'{{ item.name }}' not in existing_vm.list_vms"
      loop: "{{ vms }}"
        
   
      

   