# ---
# - name: kvm provision
#   hosts: localhost
#   become: true
#   tasks:
    - ansible.builtin.shell:
        ls /tmp/
      register: check_template
      
    - ansible.builtin.debug:
        msg: IN
      when: "'{{ temlate_image_name }}' in check_template.stdout"
    
        
    - ansible.builtin.get_url:
        url: "{{ template_image_url }}"
        dest: "/tmp/{{ temlate_image_name }}"
      when: "'{{ temlate_image_name }}' not in check_template.stdout"
        
        
    # - name: copy template image
    #   ansible.builtin.copy:
    #     src: /{{ libvirt_pool_dir }}/vm-template.qcow2
    #     dest: /{{ libvirt_pool_dir }}/{{ item.name }}.qcow2
    #   register: copy_res
    #   loop: "{{ vms }}"
      
    # - name: configure image
    #   ansible.builtin.shell:
    #     virt-customize -a {{ libvirt_pool_dir }}/{{ item.name }}.qcow2 \
    #     --hostname {{ item.name }} \
    #     --ssh-inject 'vlad:file:{{ ssh_key }}' 
    #   loop: "{{ vms }}"
    #   when: copy_res is changed

        
    # - name: create vm
    #   community.libvirt.virt:
    #     name: "{{ item.name }}"
    #     command: define
    #     xml: "{{ lookup('template', './template/template-vm.xml.j2') }}"
    #   loop: "{{ vms }}"
