---
- name: setup
  hosts: all
  become: true
  vars:
    user: alex
  tasks: 
    - name: Get  user info
      ansible.builtin.getent:
        database: group
        split: ':'
    - ansible.builtin.debug:
        var: getent_group
        