---
 - name: create user
   hosts: rocky
   become: true
   vars: 
          password: "{{ lookup('password', 'credentinals/' + item,  'lenghts=10') }}"
   tasks:
      - name: check password
        ansible.builtin.debug:
          msg: password for {{ item }} is {{ password }}
        loop: "{{ query('lines', 'cat ./user.txt') }}"
     
      - name: create user from file  
        ansible.builtin.user:
          name: "{{item}}"
          password: "{{ password | password_hash('sha512')}}"
          groups:
            - wheel
          
          state: present
        loop: "{{ query('lines', 'cat ./user.txt') }}"
      
      - name: add key
        ansible.posix.authorized_key:
          user: "{{ item}}"
          state: present
          key: "{{ lookup('file', './id_rsa.pub') }}" 
        loop: "{{ query('lines', 'cat ./user.txt') }}"
