---
- name: useradd
  hosts: rocky
  become: true
  tasks:
    - name: useradd
      vars:
        password: "{{ lookup('password', 'credentinals/' + item.name + 'lenghts=9') }}"
      
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ password | password_hash('sha512')}}"
        update_password: on_create
        groups: "{{ item.groups }}"
        shell: "{{ item.shell | default('/bin/bash') }}"
        state: present
      loop: "{{ user }}"
     
    

    - name: add ssh key
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('file', './id_rsa.pub') }}"
      loop: "{{ user }}"