---
- name: copy {{ temlate_image_name }} to {{ libvirt_pool_dir }}
  ansible.builtin.copy:
    src: /tmp/{{ temlate_image_name }}
    dest: /{{ libvirt_pool_dir }}/{{ item.name }}.qcow2
    force: no
    remote_src: yes 
    mode: 0660
  register: copy_result
  loop: "{{ vms }}"

- name: customize temlate
  ansible.builtin.shell:
    virt-customize -a {{ libvirt_pool_dir }}/{{ item.name }}.qcow2 \
    --hostname {{ item.name }} \
    --root-password password:{{ vm_root_pass }} \
    --ssh-inject 'root:file:{{ ssh_key }}' \
    --uninstall createcloud-init --selinux-relabel
  when: copy_result is changed
  loop: "{{ vms }}"    

- name: define vm
  community.libvirt.virt:
    name: "{{ item.name }}"
    command: define
    xml: "{{ lookup('template', 'template-vm.xml.j2') }}"
  when: "'{{ item.name }}' not in existing_vm.list_vms"
  loop: "{{ vms }}"
  
