---
- name: update package
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true

- name: install soft
  ansible.builtin.apt:
    name: "{{ soft }}"
    state: present
    update_cache: true
  notify: start_service 
      
