---
# tasks file for baseprovision
- name: include OS vars
  include_vars: "{{ ansible_facts.distribution}}.yaml"

- name: add users to Ubuntu
  ansible.builtin.import_tasks: useradd.yaml
  when: ansible_facts['distribution'] == "Ubuntu"

- name: add users to Rocky
  ansible.builtin.import_tasks: useradd.yaml  
  when: ansible_facts['distribution'] == "Rocky"

- name: install soft
  ansible.builtin.import_tasks: apt.yaml
  when: ansible_facts['distribution'] == "Ubuntu"
          
- name: install soft Rocky
  ansible.builtin.import_tasks: yum.yaml   
  when: ansible_facts['distribution'] == "Rocky"