- name: add user
  ansible.builtin.user:
      name: "{{ item.name }}"
      password: "{{ item.password | password_hash('sha512') }}"
      groups: "{{ item.groups }}"
      shell: "{{ item.shell | default('/bin/bash')}}"
      state: present
      update_password: on_create
  loop: "{{ user }}"    

- name: add ssh key 
  ansible.posix.authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "{{ lookup('file', 'id_rsa.pub') }}"
  loop: "{{ user }}"
  