

- name: add gpg key
  ansible.builtin.apt_key:
    url: "{{ url_ubuntu }}"
    state: present
    validate_certs: no

- name: add repo
  ansible.builtin.apt_repository:
    repo:  "{{ repo_ubuntu }}"
    state: present
          
- name: install docker soft
  ansible.builtin.apt:
    name: "{{ soft }}"
    state: latest
    update_cache: true
  
- ansible.builtin.service_facts:
  notify: service started
  when: "item  in ansible_facts.services"
  loop: "{{ service_name }}"